name: music_download_youtube
version: 1.0.2+6
publish_to: none
description: Video Mp3 Downloader
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.1.1
  flutter_svg: 2.0.9
  cached_network_image: 3.3.1
  google_fonts: 4.0.3
  lazy_load_scrollview: 1.3.0
  sizer: 2.0.15
  introduction_screen: 3.1.12
  shared_preferences: 2.2.2
  freezed_annotation: 2.2.0
  retrofit: 4.0.1
  json_annotation: 4.8.1
  http: 0.13.5
  intl: 0.19.0
  path_provider: 2.0.11
  audio_video_progress_bar: 2.0.1
  just_audio: 0.9.36
  lottie: 2.7.0
  just_audio_background: 0.0.1-beta.11
  change_app_package_name: 1.1.0
  connectivity_plus: 5.0.2
  fluttertoast: 8.2.4
  in_app_review: 2.0.8
  rating_dialog: 2.0.4
  url_launcher: 6.2.4
  receive_sharing_intent: 1.6.7
  package_info_plus: 4.2.0
  flutter_file_dialog: 3.0.2
  chunked_downloader: 0.0.2
  async: 2.11.0
  # flutter_youtube_downloader: 0.0.5
  youtube_data_api: 1.0.4
  youtube_player_flutter: 8.1.2
  video_player: 2.8.2
  chewie: 1.7.4
  simple_animations: 5.0.2
  file_picker: 6.1.1
  permission_handler: 11.0.0
  flutter_slidable: 3.0.1
  unity_ads_plugin: 0.3.8
  flutter_dotenv: 5.1.0
  build_runner: 2.4.5
  dartz: 0.10.1
  path: ^1.8.3
  youtube_explode_dart: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  assets_scanner: 2.0.0
  freezed: 2.3.5
  json_serializable: 6.7.0
  retrofit_generator: 7.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - google_fonts/
    - .env
  uses-material-design: true

