/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class MainAssets {
  static const package = 'music_download_youtube';

  static const astro = 'assets/astro.json';

  static const ic_trash2 = 'assets/ic_trash2.svg';

  static const ic_more_more = 'assets/ic_more_more.svg';

  static const ic_share = 'assets/ic_share.svg';

  static const empty_video = 'assets/empty_video.svg';

  static const repeat = 'assets/repeat.svg';

  static const ic_fire = 'assets/ic_fire.svg';

  static const ic_backward = 'assets/ic_backward.svg';

  static const empty_search = 'assets/empty_search.svg';

  static const ic_plus = 'assets/ic_plus.svg';

  static const ic_add = 'assets/ic_add.svg';

  static const loading = 'assets/loading.json';

  static const ic_audio_downloaded = 'assets/ic_audio_downloaded.svg';

  static const ic_forward = 'assets/ic_forward.svg';

  static const ic_play2 = 'assets/ic_play2.svg';

  static const ic_home = 'assets/ic_home.svg';

  static const ic_close = 'assets/ic_close.svg';

  static const ic_user = 'assets/ic_user.svg';

  static const ic_start = 'assets/ic_start.svg';

  static const repeat_one = 'assets/repeat_one.svg';

  static const ic_list_music2 = 'assets/ic_list_music2.svg';

  static const ic_pause2 = 'assets/ic_pause2.svg';

  static const ic_like = 'assets/ic_like.svg';

  static const img_empty = 'assets/img_empty.jpg';

  static const image_kosong = 'assets/image_kosong.png';

  static const ic_tag = 'assets/ic_tag.svg';

  static const ic_video_error = 'assets/ic_video_error.svg';

  static const logo_music = 'assets/logo_music.svg';

  static const ic_youtube = 'assets/ic_youtube.svg';

  static const ic_trash = 'assets/ic_trash.svg';

  static const warning = 'assets/warning.svg';

  static const ic_home2 = 'assets/ic_home2.svg';

  static const img_kosong = 'assets/img_kosong.png';

  static const empty_sound2 = 'assets/empty_sound2.svg';

  static const empty_sound3 = 'assets/empty_sound3.svg';

  static const ic_earphone = 'assets/ic_earphone.svg';

  static const ic_download3 = 'assets/ic_download3.svg';

  static const ic_img_empty = 'assets/ic_img_empty.svg';

  static const ic_download2 = 'assets/ic_download2.svg';

  static const logo = 'assets/logo.png';

  static const splash2 = 'assets/splash2.json';

  static const ic_list_music = 'assets/ic_list_music.svg';

  static const ic_plus2 = 'assets/ic_plus2.svg';

  static const ic_eye_on = 'assets/ic_eye_on.svg';

  static const ic_download4 = 'assets/ic_download4.svg';

  static const ic_wave = 'assets/ic_wave.svg';

  static const ic_like2 = 'assets/ic_like2.svg';

  static const ic_video_downloaded = 'assets/ic_video_downloaded.svg';

  static const ic_downloaded = 'assets/ic_downloaded.svg';

  static const ic_play = 'assets/ic_play.svg';

  static const ic_download = 'assets/ic_download.svg';

  static const empty_sound = 'assets/empty_sound.svg';

  static const ic_headset_logo = 'assets/ic_headset_logo.svg';

  static const ic_eye_off = 'assets/ic_eye_off.svg';

  static const ic_settings = 'assets/ic_settings.svg';

  static const empty_sound4 = 'assets/empty_sound4.png';

  static const shuffle = 'assets/shuffle.svg';

  static const ic_music = 'assets/ic_music.svg';

  static const ic_headset = 'assets/ic_headset.svg';

  static const ic_next = 'assets/ic_next.svg';

  static const sound_wave = 'assets/sound_wave.json';

  static const loading_play = 'assets/loading_play.json';

  static const ic_settings2 = 'assets/ic_settings2.svg';

  static const ic_more = 'assets/ic_more.svg';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
